version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - npm i
      - apt-get update
      - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Starting the build phase...
      - cd server/
      - gradle clean test
      - gradle clean build
      - cd ..
      - cd client/
      - npm ci
      - npm run dev &
      - npx cypress run
  post_build:
    commands:
      - echo Build phase completed.
