version: 0.2

phases:
  install:
    commands:
      - npm ci
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Starting the build phase...
      - cd server/
      - gradle clean test
      - gradle clean build
      - cd ..
      - cd client/
      - npm run start
      - npx cypress run
  post_build:
    commands:
      - echo Build phase completed.
