version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Starting the build phase...
      - gradle clean build
  post_build:
    commands:
      - echo Build phase completed.
artifacts:
  files:
    - build/libs/*.jar