version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm run cy:verify
      - npm run cy:info
  build:
    commands:
      - echo Starting the build phase...
      - cd server/
      - gradle clean test
      - gradle clean build
      - npm run start:ci &
      - npx cypress run --record
  post_build:
    commands:
      - echo Build phase completed.
