import './globals.css'
import type { Metadata } from 'next'
import theme from './theme'
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from '@mui/material/';
import Header from './header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline>
          <body>
          <Header />
          {children}
          </body>
        </CssBaseline>
      </ThemeProvider>
    </html>
  )
}
