version = 0.1
[default.deploy.parameters]
stack_name = "agluwiq-stack"
resolve_s3 = true
s3_prefix = "agluwiq-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
image_repositories = []
