import type { Metadata } from "next";
import Header from "../header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AccountLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <section style={{ padding: "0px 20px" }}>{children}</section>
    </div>
  );
}
